<l>s/	lb	/	lbc	<t>,/g
<l>s/	lh	/	lhc	<t>,/g
<l>s/	lw	/	lwc	<t>,/g
<l>s/	ld	/	ldc	<t>,/g
<l>s/	lbu	/	lbuc	<t>,/g
<l>s/	lhu	/	lhuc	<t>,/g
<l>s/	lwu	/	lwuc	<t>,/g
<l>s/	sb	/	sbct	<t>,<t>,/g
<l>s/	sh	/	shct	<t>,<t>,/g
<l>s/	sw	/	swct	<t>,<t>,/g
<l>s/	sd	/	sdct	<t>,<t>,/g
